# Generated by Django 5.1.4 on 2026-06-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diplomas_app", "0010_cursoempleado_correos_notificacion"),
    ]

    operations = [
        migrations.CreateModel(
            name="FraseMotivacional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frase", models.CharField(max_length=500)),
                ("personaje", models.CharField(max_length=100)),
            ],
        ),
    ]
