# Generated by Django 5.1.4 on 2026-06-19 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diplomas_app", "0011_frasemotivacional"),
        ("empleados_app", "0004_alter_datosbasicosempleado_grupo_etnico"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cursoempleado",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="cursoempleado",
            name="participante_apellidos",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="cursoempleado",
            name="participante_cargo",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="cursoempleado",
            name="participante_institucion",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="cursoempleado",
            name="empleado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cursos",
                to="empleados_app.empleado",
            ),
        ),
        migrations.AlterField(
            model_name="cursoempleado",
            name="participante_dpi",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="cursoempleado",
            name="participante_nombre",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddConstraint(
            model_name="cursoempleado",
            constraint=models.UniqueConstraint(
                condition=models.Q(("participante_dpi", ""), _negated=True),
                fields=("curso", "participante_dpi"),
                name="unique_diploma_participant_dpi_per_course",
            ),
        ),
    ]
