# Generated by Django 5.1.4 on 2026-06-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diplomas_app", "0012_alter_cursoempleado_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionGeneral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_institucion",
                    models.CharField(
                        default="Unidad para la Prevención Comunitaria de la Violencia",
                        max_length=200,
                    ),
                ),
                ("direccion", models.CharField(blank=True, max_length=255, null=True)),
                ("telefono", models.CharField(blank=True, max_length=50, null=True)),
                ("correo", models.EmailField(blank=True, max_length=254, null=True)),
                ("sitio_web", models.URLField(blank=True, null=True)),
                (
                    "logotipo",
                    models.ImageField(
                        blank=True, null=True, upload_to="configuracion/logos/"
                    ),
                ),
                (
                    "logotipo2",
                    models.ImageField(
                        blank=True, null=True, upload_to="configuracion/logos/"
                    ),
                ),
                (
                    "sello",
                    models.ImageField(
                        blank=True, null=True, upload_to="configuracion/sellos/"
                    ),
                ),
                (
                    "firma_autoridad",
                    models.ImageField(
                        blank=True, null=True, upload_to="configuracion/firmas/"
                    ),
                ),
                (
                    "nombre_autoridad",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "cargo_autoridad",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("actualizado", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuración general",
                "verbose_name_plural": "Configuración general",
            },
        ),
    ]
